# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HXaq51maj4FFXMbZVHxKVL22OEekc_D
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import joblib
import numpy as np
import os
import sys

class SimpleLinearRegression:
    def __init__(self):
        self.m = 0
        self.b = 0

    def fit(self, X, y):
        pass

    def predict(self, X):
        X_array = np.array(X)
        predictions = self.m * X_array + self.b
        return np.round(np.clip(predictions, 0, 100))

app = FastAPI(
    title="Student Grade Predictor API",
    description="A simple Linear Regression model to predict grades based on study hours.",
    version="1.0.0"
)

model = None

@app.on_event("startup")
def load_model():
    global model
    model_path = "model.pkl"

    if not os.path.exists(model_path):
        print(f"Warning: {model_path} not found. Running with empty model.")
        model = SimpleLinearRegression()
        return

    try:
        import __main__
        setattr(__main__, "SimpleLinearRegression", SimpleLinearRegression)
        # -----------------------

        model = joblib.load(model_path)
        print("Model loaded successfully")
    except Exception as e:
        print(f"Error loading model: {e}")
        model = SimpleLinearRegression()


class PredictionRequest(BaseModel):
    study_hours: float

@app.get("/")
def home():
    return {"message": "Welcome to Grade Predictor API. Go to /docs for usage."}

@app.post("/predict")
def predict_grade(request: PredictionRequest):
    if model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    hours = [request.study_hours]
    prediction = model.predict(hours)

    return {
        "input_hours": request.study_hours,
        "predicted_grade": int(prediction[0])
    }