# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZ4Mh933NYMmL3_dg8rSvRf_XhIxxDrw
"""

from fastmcp import FastMCP
import requests

mcp = FastMCP("Grade Predictor MCP")
API_URL = "https://midterm-backend-school-grades.onrender.com/predict"

@mcp.tool()
def get_predicted_grade(study_hours: float) -> str:
    """
    Predicts the student's exam grade based on study hours.

    Args:
        study_hours: The number of hours the student studied before the exam.

    Returns:
        A message containing the predicted grade.
    """
    try:
        payload = {"study_hours": study_hours}
        response = requests.post(API_URL, json=payload, timeout=10)

        if response.status_code == 200:
            data = response.json()
            grade = data.get("predicted_grade")
            return f"For {study_hours} hours of study, the predicted grade is {grade}."
        else:
            return f"Error: API returned status code {response.status_code}"

    except Exception as e:
        return f"Connection error: {str(e)}"

if __name__ == "__main__":
    # Run the MCP server
    mcp.run()